state_base = {
    "Qi Supply": None,
    "Quai Supply": None,
    "Block Number": None,
    "Block Difficulty": 6000,
    "Number of Regions": 2,
    "Zones per Region": 2,
    "Historical Converted Qi": None,
    "Historical Converted Quai": None,
    "Historical Mined Ratio": None,
    "Historical Qi Hash": None,
    "Historical Quai Hash": None,
    "K Qi": 1,
    "K Quai": 1,
    "Quai Price": 1,
    "Qi Price": 1,
    "Simulation History Log": None,
    "Dummy": None,
}
