state_base = {
    "Qi Supply": 10000,
    "Quai Supply": 10000,
    "Locked Qi Supply": 0,
    "Locked Quai Supply": 0,
    "Block Number": None,
    "Block Difficulty": 6000,
    "Number of Regions": 2,
    "Zones per Region": 2,
    "Historical Converted Qi": [],
    "Historical Converted Quai": [],
    "Historical Mined Ratio": None,
    "Historical Qi Hash": None,
    "Historical Quai Hash": None,
    "K Qi": 1,
    "K Quai": 1,
    "Quai Price": 1,
    "Qi Price": 1,
    "Simulation History Log": None,
    "Dummy": None,
    "Time": 0,
    "Delta Time": 0,
}
